server:
  port: 8110
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: fayupable
    password: fayupable
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.order.orderservice.kafka.OrderConfirmation


application:
  config:
    user-url: localhost:8222/user
    restaurant-url: http://localhost:8222/restaurant
    payment-url: localhost:8222/payments
    auth-url: localhost:8222/auth